version: 0.1
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: localhost:5000
  secret: supersecret
  debug:
    addr: localhost:5001
